micronaut:
  application:
    name: micronautTodo

datasources:
  default:
    url: jdbc:mariadb://localhost:330/incubyte
    username: root
    password: my-secret-pw
    packages-to-scan:
      - 'com.incubyte'
#    url: jdbc:h2:mem:devDb
#    driverClassName: org.h2.Driver
#    username: sa
#    password: ''
#    schema-generate: CREATE_DROP
#    dialect: H2
#    packages-to-scan:
#      - 'com.incubyte'
jpa:
  default:
    properties:
      hibernate:
#        hbm2ddl:
#          auto: update
        show_sql: true
liquibase:
  datasources:
    default:
      change-log: 'classpath:db/liquibase-changelog.sql'